companies:
  - 阿里
  - 腾讯
  - 百度在线 # 直接输入百度会跳到企查查，得百度在线
  - 抖音 # 字节跳动更名了
  - 百川智能 # 直接百川会搜到其他公司
  - 智谱
  - 月之暗面
  - 阶跃星辰
  - MiniMax # minimax 是可以正确定位到稀宇科技的
  - 零一万物
fields:
  table:
    - '统一社会信用代码'
    - '企业名称 '
    - '法定代表人 '
    - '登记状态 '
    - '注册资本 '
    - '成立日期	'
    - '实缴资本 '
    - '组织机构代码 '
    - '工商注册号 '
    - '纳税人识别号 '
    - '企业类型	'
    - '营业期限 '
    - '纳税人资质 '
    - '人员规模	'
    - '参保人数	'
    - '核准日期 '
    - '所属地区	'
    - '登记机关 '
    - '国标行业 '
    - '英文名	'
    - '注册地址 '
    - '经营范围 '